// Diccionario de Idiomas
const diccionario = {
    en: {
        "app-title": "Falcon Ventures: Private Equity",
        "app-description": "Private Business Group investing in early or growth-stage security companies.",
        "nav-home": "Home",
        "nav-about": "About",
        "nav-news": "News",
        "nav-portfolio": "Portfolio",
        "nav-team": "Team",
        "nav-contact": "Contact",
        "nav-consulting": "Consulting",
        "about-kicker": "About",
        "about-title": "Falcon Ventures Private Business Group",
        "about-description": "We are a Private Business Group that invests in security sector small and medium sized companies, we invest in <span>early-stage</span> or <span>growth-stage</span> companies in the security industry.",
        "hero-title": "Investing in a safe Future",
        "hero-subtitle": "Private Equity & Business Group",
        "investing-in-a-safe-Future": "Investing in a safe future",
        "hero-bg-alt": "Safe Future",
        "about-page-title": "We look for a <span class=\"text-indigo\">safer world.</span>",
        "about-page-image-alt": "Strategic Oversight",
        "about-page-tag": "COMPANY PROFILE",
        "about-page-headline": "We are a <span class=\"weight-700\">private business group</span> that invests in security sector small and medium sized companies.",
        "about-page-description": "We focus on early-stage or growth-stage companies within the security industry. These ventures develop cutting-edge technologies in <span class=\"inline-bold\">cyber security</span>, <span class=\"inline-bold\">physical security</span>, and <span class=\"inline-bold\">mission-critical communications</span>.",
        "about-page-secondary": "Our management team conducts extensive due diligence and provides strategic oversight to ensure technological leadership.",
        "envia-mensaje":"Send Us a Message",
        "footer-subtitle": "Private Business Group",
        "footer-social-title": "Social media",
        "footer-language-title": "Language",
        "footer-location-title": "Location",
        "footer-address-value": "Sierra Mojada 446, Lomas de Chapultepec III Section, Miguel Hidalgo, 11000 Mexico City, CDMX",
        "form-name-placeholder": "Your full name",
        "form-email-placeholder": "Email address",
        "form-message-placeholder": "How can we help you?",
        "form-submit": "Send Message",
        "footer-form-sending": "Sending message...",
        "footer-form-success": "Your message was sent successfully.",
        "footer-form-error": "We could not send your message right now.",
        "contact-form-sending": "Sending message...",
        "contact-form-success": "Your message was sent successfully.",
        "contact-form-error": "We could not send your message right now.",
        "validation-required": "Required field",
        "validation-footer-name": "Enter your name",
        "validation-footer-email": "Enter your email",
        "validation-footer-message": "Enter your message",
        "validation-contact-first-name": "Enter your first name",
        "validation-contact-last-name": "Enter your last name",
        "validation-contact-email": "Enter your email",
        "validation-contact-subject": "Select a subject",
        "validation-contact-message": "Enter your message",
        "validation-login-email": "Enter your email",
        "validation-login-password": "Enter your password",
        "validation-email-invalid": "Enter a valid email",
        "validation-phone-invalid": "Enter a 10-digit phone number",
        "login-success-kicker": "Welcome",
        "login-success-title": "Your access is ready",
        "login-success-text": "Here is your link.",
        "login-success-link": "Open your link",
        "login-logo-alt": "Falcon Ventures Logo",
        "login-title": "Log In",
        "login-subtitle": "Enter your credentials to continue.",
        "login-email-label": "Email",
        "login-email-placeholder": "user@falconventures.net",
        "login-password-label": "Password",
        "login-password-placeholder": "••••••••",
        "login-forgot-password": "Access issues?",
        "login-submit": "Sign in",
        "footer-copy": "© 2026 by Falcon Ventures Private Business Group. Powered and secured by intel",
        "industry-01": "INDUSTRY 01",
        "industry-02": "INDUSTRY 02",
        "industry-03": "INDUSTRY 03",
        "industry-04": "INDUSTRY 04",
        "industry-05": "INDUSTRY 05",
        "industry-06": "INDUSTRY 06",
        "industry-private-security": "PRIVATE<br />SECURITY",
        "industry-communications": "COMMUNICATIONS",
        "industry-technology": "TECHNOLOGY",
        "industry-surveillance": "SURVEILLANCE",
        "industry-artificial-intelligence": "ARTIFICIAL<br />INTELLIGENCE",
        "industry-real-estate": "REAL<br />ESTATE",
        "stat-partners": "Partners",
        "stat-employees": "Employees",
        "stat-investments": "Investments",
        "stat-success": "Success",
        "news-section-title": "Recent News",
        "news-1-alt": "Venture Capital in Latin America",
        "news-1-category": "Industry",
        "news-1-title": "Venture Capital gains ground in Latin America",
        "news-1-excerpt": "Jose Carlos Mapelli Mozzi, Chairman of Falcon Ventures, analyzes the growth of startup investment and Mexico's key role.",
        "news-1-link": "Read on Reforma",
        "news-2-alt": "Zascita Outstanding Company",
        "news-2-date": "Feb 21, 2024",
        "news-2-category": "Portfolio",
        "news-2-title": "Zascita de Mexico receives recognition as an \"Outstanding Company\"",
        "news-2-excerpt": "The Business Coordinating Council honors Zascita, a portfolio company that achieved 180% growth.",
        "news-2-link": "Read on Mundo Ejecutivo",
        "news-3-alt": "Award in Private Security",
        "news-3-date": "Feb 21, 2024",
        "news-3-category": "Impact",
        "news-3-title": "Portfolio company recognized in the private security sector",
        "news-3-excerpt": "They highlight venture capital's positive influence in the region: Falcon Ventures' strategic investment accelerated Zascita's expansion.",
        "news-3-link": "Read on El Heraldo",
        "news-4-alt": "Recognition for Company",
        "news-4-date": "2024",
        "news-4-category": "Recognition",
        "news-4-title": "Falcon Ventures company receives recognition",
        "news-4-excerpt": "Special coverage on milestones achieved by our portfolio companies, validating our focus on operational profitability.",
        "news-4-link": "Read on Reforma",
        "portfolio-kicker": "Expertise & Vision",
        "portfolio-title": "Developing the future of security",
        "portfolio-description": "Our specialized portfolio in the security sector includes investments in companies that provide security services and products, such as surveillance systems, secure communications, and security personnel. It may also include companies in related sectors such as defense, intelligence, and emergency management, depending on the group's strategy and investment objectives.",
        "portfolio-current-label": "02. Current Investments",
        "portfolio-past-label": "00. Past Investments",
        "portfolio-case-study": "CASE STUDY",
        "portfolio-zascita-alt": "Zascita de Mexico",
        "portfolio-prodao-alt": "Prodao Automation",
        "portfolio-empty-title": "0",
        "portfolio-empty-desc": "No completed investments to date. All our current assets continue on a path of strategic growth.",
        "portfolio-quote-1": "\"The private security sector is a large and rapidly growing market, with a global value projected to reach $284.5 billion by 2025. Factors such as increasing crime rates and the need for protection of critical infrastructure have significantly increased demand.\"",
        "portfolio-quote-2": "\"The growing awareness and adoption of technology in security systems is driving the sector's expansion, creating unique opportunities for strategic investment in specialized firms that lead the digital transformation of defense.\"",
        "portfolio-quote-author": "Jose Carlos Mapelli",
        "portfolio-tech-integrated-security": "Integrated Security",
        "portfolio-tech-automation": "Automation",
        "portfolio-testimonials-kicker": "Commentary",
        "portfolio-testimonials-title": "Industry perspective",
        "contact-kicker": "Contact",
        "contact-title": "Let's talk about the future",
        "contact-description": "For any information, please call us or send us an email. Alternatively, you can complete the contact form below and our management team will get back to you shortly.",
        "contact-office-label": "Our Headquarters",
        "contact-address-label": "Address",
        "contact-address-value": "Sierra Mojada #446<br>Lomas de Chapultepec, Mexico City",
        "contact-phone-label": "Phone",
        "contact-phone-value": "+52 56 2554 5521",
        "contact-email-label": "Email",
        "contact-email-value": "info@falconventures.net",
        "contact-form-label": "Send us a message",
        "contact-first-name-label": "First name",
        "contact-first-name-placeholder": "Ex. Carlos",
        "contact-last-name-label": "Last name",
        "contact-last-name-placeholder": "Ex. Mendoza",
        "contact-email-field-label": "Email address",
        "contact-email-field-placeholder": "email@company.com",
        "contact-phone-field-label": "Phone (Optional)",
        "contact-phone-field-placeholder": "+52 55 0000 0000",
        "contact-subject-label": "Subject",
        "contact-subject-placeholder": "Select an option...",
        "contact-subject-investment": "Investment Opportunity",
        "contact-subject-consulting": "Strategic Consulting",
        "contact-subject-press": "Press and Media",
        "contact-subject-other": "Other",
        "contact-message-label": "Message",
        "contact-message-placeholder": "How can we help you?",
        "contact-submit": "Send Message",
        "editorial-all-posts": "All Posts",
        "editorial-empty-title": "Check back soon.",
        "editorial-empty-desc": "Once posts are published, you’ll see them here.",
        "team-kicker": "Our team",
        "team-title": "Leadership, experience and execution to build sustainable value.",
        "team-description-1": "Our team is made up of a diverse group of professionals with a wide range of skills and experience.",
        "team-description-2": "All key team members combine industry expertise, investment experience, and operational capabilities, along with a shared passion for the security industry and a commitment to delivering strong returns for investors.",
        "team-main-image-alt": "Falcon Ventures team",
        "team-section-1": "01. Corporate Governance",
        "team-section-2": "02. Executive Team",
        "team-mapelli-role": "Chairman / Founder",
        "team-mapelli-bio": "Chairman of the Board of Directors. Responsible for overall strategy, decision-making, and investments. Extensive experience in private equity and venture capital, along with a strong network of contacts and relationships in the financial sector.",
        "team-julianis-role": "Board Member",
        "team-julianis-bio": "Expertise",
        "team-ramirez-role": "Board Member",
        "team-ramirez-bio": "Experience",
        "team-arnoldi-role": "Investment Professional",
        "team-arnoldi-bio": "Identify, analyze, and execute investments in security startups. Strong knowledge of the security sector and the ability to identify promising startups.",
        "team-fernandez-role": "Operating Partner",
        "team-fernandez-bio": "Thanks to his practical experience in the security sector, the team will help portfolio companies grow and develop.",
        "team-gutierrez-role": "Legal and Regulatory Compliance",
        "team-gutierrez-bio": "Responsible for the legal and compliance team to ensure that the fund complies with all relevant laws and regulations, and that all investments are made in accordance with the fund's investment criteria.",
        "team-escalante-role": "Finance and Accounting",
        "team-escalante-bio": "Identify, analyze, and execute investments in security startups. Strong knowledge of the security sector and the ability to identify promising startups.",
        "team-escamilla-role": "Marketing and Communications",
        "team-escamilla-bio": "The head of the marketing and communications team is responsible for promoting the fund and its portfolio companies, as well as communicating with investors.",
        "team-vazquez-role": "CTO",
        "team-vazquez-bio": "Head of technology",
        "error-code": "Error 404",
        "error-title": "Page not found",
        "error-description": "The route you tried to open does not exist or has not been created in the project yet.",
        "error-back-home": "Back to home"
    },
    es: {
        "app-title": "Falcon Ventures: Capital Privado",
        "app-description": "Grupo privado de negocios que invierte en empresas de seguridad en etapa temprana o de crecimiento.",
        "nav-home": "Inicio",
        "nav-about": "Acerca de",
        "nav-news": "Noticias",
        "nav-portfolio": "Cartera",
        "nav-team": "Equipo",
        "nav-contact": "Contacto",
        "nav-consulting": "Consultoría",
        "about-kicker": "Acerca de Nosotros",
        "about-title": "Falcon Ventures Private Business Group",
        "about-description": "Somos un grupo privado de negocios que invierte en pequenas y medianas empresas del sector de seguridad; invertimos en companias en etapa <span>temprana</span> o en <span>crecimiento</span> dentro de la industria de seguridad.",
        "hero-title": "Invirtiendo en un futuro seguro",
        "hero-subtitle": "Grupo de Capital Privado y Negocios",
        "investing-in-a-safe-Future": "Invertir en un futuro seguro",
        "hero-bg-alt": "Futuro seguro",
        "about-page-title": "Buscamos un <span class=\"text-indigo\">mundo más seguro.</span>",
        "about-page-image-alt": "Supervisión estratégica",
        "about-page-tag": "PERFIL DE LA EMPRESA",
        "about-page-headline": "Somos un <span class=\"weight-700\">grupo privado de negocios</span> que invierte en pequeñas y medianas empresas del sector de seguridad.",
        "about-page-description": "Nos enfocamos en empresas en etapa temprana o de crecimiento dentro de la industria de la seguridad. Estas compañías desarrollan tecnologías de vanguardia en <span class=\"inline-bold\">ciberseguridad</span>, <span class=\"inline-bold\">seguridad física</span> y <span class=\"inline-bold\">comunicaciones de misión crítica</span>.",
        "about-page-secondary": "Nuestro equipo directivo realiza una debida diligencia exhaustiva y aporta supervisión estratégica para asegurar el liderazgo tecnológico.",
        "envia-mensaje":"Envíanos un mensaje",
        "footer-subtitle": "Grupo Privado de Negocios",
        "footer-social-title": "Redes sociales",
        "footer-language-title": "Idioma",
        "footer-location-title": "Ubicación",
        "footer-address-value": "Sierra Mojada 446, Lomas de Chapultepec III Secc, Miguel Hidalgo, 11000 Ciudad de México, CDMX",
        "form-name-placeholder": "Tu nombre completo",
        "form-email-placeholder": "Correo electrónico",
        "form-message-placeholder": "¿En qué podemos ayudarte?",
        "form-submit": "Enviar Mensaje",
        "footer-form-sending": "Enviando mensaje...",
        "footer-form-success": "Tu mensaje fue enviado correctamente.",
        "footer-form-error": "No pudimos enviar tu mensaje por ahora.",
        "contact-form-sending": "Enviando mensaje...",
        "contact-form-success": "Tu mensaje fue enviado correctamente.",
        "contact-form-error": "No pudimos enviar tu mensaje por ahora.",
        "validation-required": "Campo obligatorio",
        "validation-footer-name": "Ingresa tu nombre",
        "validation-footer-email": "Ingresa tu correo electronico",
        "validation-footer-message": "Ingresa tu mensaje",
        "validation-contact-first-name": "Ingresa tu nombre",
        "validation-contact-last-name": "Ingresa tu apellido",
        "validation-contact-email": "Ingresa tu correo electronico",
        "validation-contact-subject": "Selecciona un asunto",
        "validation-contact-message": "Ingresa tu mensaje",
        "validation-login-email": "Ingresa tu correo electronico",
        "validation-login-password": "Ingresa tu contraseña",
        "validation-email-invalid": "Ingresa un correo valido",
        "validation-phone-invalid": "Ingresa un telefono de 10 digitos",
        "login-success-kicker": "Bienvenido",
        "login-success-title": "Tu acceso ya esta listo",
        "login-success-text": "Tu link es el siguiente.",
        "login-success-link": "Ir a tu link",
        "login-logo-alt": "Logotipo de Falcon Ventures",
        "login-title": "Iniciar Sesión",
        "login-subtitle": "Introduce tus credenciales para continuar.",
        "login-email-label": "Correo Electrónico",
        "login-email-placeholder": "usuario@falconventures.net",
        "login-password-label": "Contraseña",
        "login-password-placeholder": "••••••••",
        "login-forgot-password": "¿Problemas de acceso?",
        "login-submit": "Acceder",
        "footer-copy": "© 2026 por Falcon Ventures Private Business Group. Powered and secured by intel",
        "industry-01": "INDUSTRIA 01",
        "industry-02": "INDUSTRIA 02",
        "industry-03": "INDUSTRIA 03",
        "industry-04": "INDUSTRIA 04",
        "industry-05": "INDUSTRIA 05",
        "industry-06": "INDUSTRIA 06",
        "industry-private-security": "SEGURIDAD<br />PRIVADA",
        "industry-communications": "COMUNICACIONES",
        "industry-technology": "TECNOLOGÍA",
        "industry-surveillance": "VIGILANCIA",
        "industry-artificial-intelligence": "INTELIGENCIA<br />ARTIFICIAL",
        "industry-real-estate": "BIENES<br />RAÍCES",
        "stat-partners": "Socios",
        "stat-employees": "Empleados",
        "stat-investments": "Inversiones",
        "stat-success": "Éxito",
        "news-section-title": "Noticias Recientes",
        "news-1-alt": "Venture Capital en America Latina",
        "news-1-category": "Industria",
        "news-1-title": "Venture Capital gana terreno en America Latina",
        "news-1-excerpt": "Jose Carlos Mapelli Mozzi, presidente del Consejo de Falcon Ventures, analiza el crecimiento de la inversion en startups y el papel clave de Mexico.",
        "news-1-link": "Leer en Reforma",
        "news-2-alt": "Zascita Empresa Excepcional",
        "news-2-date": "21 Feb 2024",
        "news-2-category": "Portafolio",
        "news-2-title": "Zascita de Mexico recibe reconocimiento como \"Empresa Excepcional\"",
        "news-2-excerpt": "El Consejo Coordinador Empresarial galardona a Zascita, empresa de nuestro portafolio que experimento un crecimiento del 180%.",
        "news-2-link": "Leer en Mundo Ejecutivo",
        "news-3-alt": "Galardon en Seguridad Privada",
        "news-3-date": "21 Feb 2024",
        "news-3-category": "Impacto",
        "news-3-title": "Galardonan a firma del portafolio en el sector de seguridad privada",
        "news-3-excerpt": "Destacan la influencia positiva del venture capital en la region: la inversion estrategica de Falcon Ventures acelero la expansion de Zascita.",
        "news-3-link": "Leer en El Heraldo",
        "news-4-alt": "Reconocimiento a Compania",
        "news-4-date": "2024",
        "news-4-category": "Reconocimiento",
        "news-4-title": "Reconocen a compania de Falcon Ventures",
        "news-4-excerpt": "Cobertura especial sobre los hitos alcanzados por las empresas de nuestro portafolio, validando nuestro enfoque en la rentabilidad operativa.",
        "news-4-link": "Leer en Reforma",
        "portfolio-kicker": "Experiencia y Visión",
        "portfolio-title": "Desarrollando el futuro de la seguridad",
        "portfolio-description": "Nuestra cartera especializada en el sector de la seguridad incluye inversiones en empresas que ofrecen servicios y productos de seguridad, como sistemas de vigilancia, comunicaciones seguras y personal de seguridad. También puede incluir empresas de sectores afines, como defensa, inteligencia y gestión de emergencias, según la estrategia y los objetivos de inversión del grupo.",
        "portfolio-current-label": "02. Inversiones Actuales",
        "portfolio-past-label": "00. Inversiones Pasadas",
        "portfolio-case-study": "CASO DE ESTUDIO",
        "portfolio-zascita-alt": "Zascita de México",
        "portfolio-prodao-alt": "Prodao Automatización",
        "portfolio-empty-title": "0",
        "portfolio-empty-desc": "Sin inversiones finalizadas hasta la fecha. Todos nuestros activos actuales mantienen un crecimiento estratégico.",
        "portfolio-quote-1": "\"El sector de la seguridad privada es un mercado grande y de rápido crecimiento, con un valor global proyectado de 284.5 mil millones de dólares para 2025. Factores como el aumento de la criminalidad y la necesidad de proteger infraestructura crítica han incrementado significativamente la demanda.\"",
        "portfolio-quote-2": "\"La creciente conciencia y adopción de tecnología en los sistemas de seguridad está impulsando la expansión del sector, creando oportunidades únicas para la inversión estratégica en firmas especializadas que lideran la transformación digital de la defensa.\"",
        "portfolio-quote-author": "Jose Carlos Mapelli",
        "portfolio-tech-integrated-security": "Seguridad Integrada",
        "portfolio-tech-automation": "Automatización",
        "portfolio-testimonials-kicker": "Comentarios",
        "portfolio-testimonials-title": "Perspectiva del sector",
        "contact-kicker": "Contacto",
        "contact-title": "Hablemos de futuro",
        "contact-description": "Para cualquier información, por favor llámenos o envíenos un correo electrónico. Alternativamente, puede completar el siguiente formulario de contacto y nuestro equipo de gestión se comunicará con usted a la brevedad.",
        "contact-office-label": "Nuestra Sede",
        "contact-address-label": "Dirección",
        "contact-address-value": "Sierra Mojada #446<br>Lomas de Chapultepec, CDMX",
        "contact-phone-label": "Teléfono",
        "contact-phone-value": "+52 56 2554 5521",
        "contact-email-label": "Email",
        "contact-email-value": "info@falconventures.net",
        "contact-form-label": "Envíenos un mensaje",
        "contact-first-name-label": "Nombre",
        "contact-first-name-placeholder": "Ej. Carlos",
        "contact-last-name-label": "Apellido",
        "contact-last-name-placeholder": "Ej. Mendoza",
        "contact-email-field-label": "Correo Electrónico",
        "contact-email-field-placeholder": "correo@empresa.com",
        "contact-phone-field-label": "Teléfono (Opcional)",
        "contact-phone-field-placeholder": "+52 55 0000 0000",
        "contact-subject-label": "Asunto",
        "contact-subject-placeholder": "Seleccione una opción...",
        "contact-subject-investment": "Oportunidad de Inversión",
        "contact-subject-consulting": "Consultoría Estratégica",
        "contact-subject-press": "Prensa y Medios",
        "contact-subject-other": "Otro",
        "contact-message-label": "Mensaje",
        "contact-message-placeholder": "¿En qué podemos ayudarle?",
        "contact-submit": "Enviar Mensaje",
        "editorial-all-posts": "Todas las publicaciones",
        "editorial-empty-title": "Vuelve pronto.",
        "editorial-empty-desc": "Cuando se publiquen entradas, las verás aquí.",
        "team-kicker": "Nuestro equipo",
        "team-title": "Liderazgo, experiencia y ejecucion para construir valor sostenible.",
        "team-description-1": "Nuestro equipo está formado por un grupo diverso de profesionales con una amplia variedad de habilidades y experiencias.",
        "team-description-2": "Todos los miembros clave del equipo pueden combinar experiencia en el sector, experiencia en inversiones y capacidades operativas, así como una pasión compartida por la industria de la seguridad y el compromiso de generar altos rendimientos para los inversores.",
        "team-main-image-alt": "Equipo Falcon Ventures",
        "team-section-1": "01. Gobierno Corporativo",
        "team-section-2": "02. Equipo Directivo",
        "team-mapelli-role": "Presidente / Fundador",
        "team-mapelli-bio": "Presidente del Consejo de Administración. Responsable de la estrategia general, la toma de decisiones y las inversiones. Amplia experiencia en el sector del capital privado y el capital riesgo, así como una sólida red de contactos y relaciones en el sector financiero.",
        "team-julianis-role": "Miembro de la Junta Directiva",
        "team-julianis-bio": "Expeetic",
        "team-ramirez-role": "Miembro de la Junta Directiva",
        "team-ramirez-bio": "Experiencia",
        "team-arnoldi-role": "Profesional de inversiones",
        "team-arnoldi-bio": "Identificar, analizar y ejecutar inversiones en startups de seguridad. Sólido conocimiento del sector de la seguridad y capacidad para identificar startups prometedoras.",
        "team-fernandez-role": "Socio Operativo",
        "team-fernandez-bio": "Gracias a su experiencia práctica en el sector de la seguridad, el equipo ayudará a las empresas de la cartera a crecer y desarrollarse.",
        "team-gutierrez-role": "Aspectos legales y cumplimiento normativo",
        "team-gutierrez-bio": "Responsable del equipo jurídico y de cumplimiento normativo para garantizar que el fondo cumpla con todas las leyes y normativas pertinentes, y que todas las inversiones se realicen de conformidad con los criterios de inversión del fondo.",
        "team-escalante-role": "Finanzas y Contabilidad",
        "team-escalante-bio": "Identificar, analizar y ejecutar inversiones en startups de seguridad. Sólido conocimiento del sector de la seguridad y capacidad para identificar startups prometedoras.",
        "team-escamilla-role": "Marketing y Comunicaciones",
        "team-escamilla-bio": "El responsable del equipo de marketing y comunicaciones se encarga de dar a conocer el fondo y las empresas que lo componen, así como de comunicarse con los inversores.",
        "team-vazquez-role": "CTO",
        "team-vazquez-bio": "Jefe de tecnología",
        "error-code": "Error 404",
        "error-title": "Página no encontrada",
        "error-description": "La ruta que intentaste abrir no existe o todavía no fue creada dentro del proyecto.",
        "error-back-home": "Volver al inicio"
    }
};

// 2. Revisamos si el usuario ya había elegido un idioma antes (por defecto será inglés 'en')
let idiomaActual = localStorage.getItem('idioma') || 'en';

// 3. Función principal que traduce toda la pantalla
function traducirPagina() {
    const traducciones = diccionario[idiomaActual] || diccionario.en;

    document.documentElement.lang = idiomaActual;

    if (traducciones["app-title"]) {
        document.title = traducciones["app-title"];
    }

    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription && traducciones["app-description"]) {
        metaDescription.setAttribute('content', traducciones["app-description"]);
    }

    // Buscamos todas las etiquetas HTML que tengan el atributo 'data-i18n'
    const elementos = document.querySelectorAll('[data-i18n]');
    
    elementos.forEach(el => {
        const clave = el.getAttribute('data-i18n'); 
        if (traducciones[clave]) {
            el.textContent = traducciones[clave];
        }
    });

    const elementosHtml = document.querySelectorAll('[data-i18n-html]');

    elementosHtml.forEach(el => {
        const clave = el.getAttribute('data-i18n-html');

        if (traducciones[clave]) {
            el.innerHTML = traducciones[clave];
        }
    });

    const placeholders = document.querySelectorAll('[data-i18n-placeholder]');

    placeholders.forEach(el => {
        const clave = el.getAttribute('data-i18n-placeholder');

        if (traducciones[clave]) {
            el.placeholder = traducciones[clave];
        }
    });

    const alts = document.querySelectorAll('[data-i18n-alt]');

    alts.forEach(el => {
        const clave = el.getAttribute('data-i18n-alt');

        if (traducciones[clave]) {
            el.alt = traducciones[clave];
        }
    });

    const errores = document.querySelectorAll('[data-i18n-error]');

    errores.forEach(el => {
        const clave = el.getAttribute('data-i18n-error');

        if (traducciones[clave]) {
            el.textContent = traducciones[clave];
        }
    });

    const btnIdioma = document.getElementById('btn-idioma');
    if(btnIdioma) {
        btnIdioma.textContent = idiomaActual === 'en' ? 'ESPAÑOL' : 'ENGLISH';
    }
}

// 4. Función para cambiar el idioma cuando hacen clic en el botón
function cambiarIdioma() {
    idiomaActual = idiomaActual === 'en' ? 'es' : 'en';
    localStorage.setItem('idioma', idiomaActual); // Guardamos la preferencia
    traducirPagina(); // Aplicamos los cambios
}